// app.js — Cuisine Predictor
// Depends on MODEL object exported from model.js (generated by the notebook)

(function () {

  // ── State ──────────────────────────────────────────────────────────────────
  let ingredients = [];

  // ── DOM refs ───────────────────────────────────────────────────────────────
  const inputEl     = document.getElementById('ingredientInput');
  const tagsWrap    = document.getElementById('tagsWrap');
  const tagsEmpty   = document.getElementById('tagsEmpty');
  const predictBtn  = document.getElementById('predictBtn');
  const btnText     = document.getElementById('btnText');
  const loadingDots = document.getElementById('loadingDots');
  const errorBox    = document.getElementById('errorBox');
  const resultPanel = document.getElementById('resultPanel');
  const resultName  = document.getElementById('resultCuisine');
  const confList    = document.getElementById('confList');

  // ── Ingredient management ──────────────────────────────────────────────────
  inputEl.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') addIngredient();
  });

  window.addIngredient = function () {
    const raw = inputEl.value.trim().toLowerCase();
    if (!raw) return;
    raw.split(',').map(s => s.trim()).filter(Boolean).forEach(function (p) {
      if (!ingredients.includes(p)) ingredients.push(p);
    });
    inputEl.value = '';
    renderTags();
  };

  window.quickAdd = function (name) {
    if (!ingredients.includes(name)) {
      ingredients.push(name);
      renderTags();
    }
  };

  window.removeIngredient = function (name) {
    ingredients = ingredients.filter(function (i) { return i !== name; });
    renderTags();
  };

  function renderTags() {
    tagsWrap.querySelectorAll('.tag').forEach(function (t) { t.remove(); });
    tagsEmpty.style.display = ingredients.length ? 'none' : 'inline';

    ingredients.forEach(function (ing) {
      const tag = document.createElement('span');
      tag.className = 'tag';
      tag.innerHTML =
        ing +
        ' <button class="tag-x" onclick="removeIngredient(\'' +
        ing.replace(/'/g, "\\'") +
        '\')">×</button>';
      tagsWrap.appendChild(tag);
    });
  }

  // ── Prediction ─────────────────────────────────────────────────────────────
  window.predict = function () {
    hideError();

    if (!ingredients.length) {
      showError('Add at least one ingredient first.');
      return;
    }

    if (typeof MODEL === 'undefined') {
      showError(
        'model.js not found. Run the export cell in the notebook, ' +
        'then place model.js in this folder.'
      );
      return;
    }

    setLoading(true);
    resultPanel.classList.remove('show');

    // Small timeout so the browser repaints the loading state first
    setTimeout(function () {
      try {
        var result = runModel(ingredients);
        showResult(result);
      } catch (err) {
        showError('Prediction failed: ' + err.message);
        console.error(err);
      } finally {
        setLoading(false);
      }
    }, 30);
  };

  // ── TF-IDF + Logistic Regression inference ─────────────────────────────────
  //
  //  The notebook uses:
  //    TfidfVectorizer(ngram_range=(1,2), min_df=3, sublinear_tf=True)
  //    LogisticRegression(C=10, ...)
  //
  //  Steps here:
  //    1. Tokenise: join ingredient list into a string, split on whitespace,
  //       then also build bigrams — mirrors sklearn's analyzer='word'.
  //    2. Count occurrences per token.
  //    3. Apply sublinear TF: tf = 1 + log(count)  (sklearn's sublinear_tf=True)
  //    4. IDF is baked into the exported coef weights, so we skip it here.
  //       (Equivalent: using raw TF scores against weights already scaled by IDF.)
  //    5. Compute raw scores: scores[c] = dot(coef[c], vec) + intercept[c]
  //    6. Softmax over scores → probabilities.
  //
  function runModel(ingredientList) {
    var vocab   = MODEL.vocab;       // token -> slim index
    var coef    = MODEL.coef;        // [n_classes][n_slim_tokens]
    var intercept = MODEL.intercept; // [n_classes]
    var classes = MODEL.classes;     // [n_classes]
    var nClasses = classes.length;
    var nFeatures = coef[0].length;

    // 1 & 2. Tokenise and count
    var text = ingredientList.join(' ').toLowerCase();
    var words = text.match(/[a-záéíóúñ]+/gi) || [];

    var counts = {};
    // Unigrams
    words.forEach(function (w) {
      counts[w] = (counts[w] || 0) + 1;
    });
    // Bigrams
    for (var i = 0; i < words.length - 1; i++) {
      var bigram = words[i] + ' ' + words[i + 1];
      counts[bigram] = (counts[bigram] || 0) + 1;
    }

    // 3. Build sparse TF vector (only tokens present in slim vocab)
    var vec = new Float64Array(nFeatures);
    Object.keys(counts).forEach(function (token) {
      if (token in vocab) {
        var idx = vocab[token];
        var tf = 1 + Math.log(counts[token]); // sublinear_tf=True
        vec[idx] = tf;
      }
    });

    // 5. Raw scores for each class
    var scores = new Float64Array(nClasses);
    for (var c = 0; c < nClasses; c++) {
      var row = coef[c];
      var s = intercept[c];
      for (var j = 0; j < nFeatures; j++) {
        s += row[j] * vec[j];
      }
      scores[c] = s;
    }

    // 6. Softmax → probabilities
    var maxScore = -Infinity;
    for (var c = 0; c < nClasses; c++) {
      if (scores[c] > maxScore) maxScore = scores[c];
    }
    var expScores = new Float64Array(nClasses);
    var sumExp = 0;
    for (var c = 0; c < nClasses; c++) {
      expScores[c] = Math.exp(scores[c] - maxScore);
      sumExp += expScores[c];
    }
    var probs = [];
    for (var c = 0; c < nClasses; c++) {
      probs.push({ cuisine: classes[c], pct: expScores[c] / sumExp });
    }

    // Sort descending
    probs.sort(function (a, b) { return b.pct - a.pct; });

    return {
      top: probs[0].cuisine,
      candidates: probs.slice(0, 5)
    };
  }

  // ── UI helpers ─────────────────────────────────────────────────────────────
  function showResult(data) {
    resultName.textContent = data.top.replace(/_/g, ' ');
    confList.innerHTML = '';

    var topPct = data.candidates[0].pct;

    data.candidates.forEach(function (item) {
      var pct = Math.round(item.pct * 100);
      var barWidth = Math.round((item.pct / topPct) * 100); // relative bar width

      var div = document.createElement('div');
      div.className = 'conf-item';
      div.innerHTML =
        '<span class="conf-name">' + item.cuisine.replace(/_/g, ' ') + '</span>' +
        '<div class="conf-track"><div class="conf-fill" data-w="' + barWidth + '"></div></div>' +
        '<span class="conf-pct">' + pct + '%</span>';
      confList.appendChild(div);
    });

    resultPanel.classList.add('show');

    // Animate bars after paint
    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        confList.querySelectorAll('.conf-fill').forEach(function (el) {
          el.style.width = el.dataset.w + '%';
        });
      });
    });
  }

  function setLoading(on) {
    predictBtn.disabled = on;
    btnText.style.display = on ? 'none' : 'inline';
    loadingDots.classList.toggle('show', on);
  }

  function showError(msg) {
    errorBox.textContent = msg;
    errorBox.classList.add('show');
  }

  function hideError() {
    errorBox.classList.remove('show');
  }

})();
